-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin_roles
(
    admin_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT admin_roles_pkey PRIMARY KEY (admin_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.admins
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp(6) without time zone,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(15) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT admins_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.alquileres
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    costo_total numeric(38, 2) NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default",
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone,
    fecha_fin timestamp(6) without time zone NOT NULL,
    fecha_inicio timestamp(6) without time zone NOT NULL,
    observaciones character varying(500) COLLATE pg_catalog."default",
    tool_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT alquileres_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.damage_reports
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    report_date date,
    reported_by character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    tool_id bigint,
    CONSTRAINT damage_reports_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.invoices
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    due_date timestamp(6) without time zone,
    invoice_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    issue_date timestamp(6) without time zone,
    notes character varying(500) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    subtotal numeric(38, 2) NOT NULL,
    tax_amount numeric(38, 2) NOT NULL,
    total_amount numeric(38, 2) NOT NULL,
    updated_at timestamp(6) without time zone,
    reservation_id bigint NOT NULL,
    CONSTRAINT invoices_pkey PRIMARY KEY (id),
    CONSTRAINT uk6t7ctxgwv5ahht8vtcn3fxow5 UNIQUE (reservation_id),
    CONSTRAINT ukl1x55mfsay7co0r3m9ynvipd5 UNIQUE (invoice_number)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    link character varying(255) COLLATE pg_catalog."default",
    message character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    read_at timestamp(6) without time zone,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    amount numeric(38, 2) NOT NULL,
    created_at timestamp(6) without time zone,
    method character varying(20) COLLATE pg_catalog."default" NOT NULL,
    payment_date timestamp(6) without time zone,
    payment_details character varying(500) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    transaction_id character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    reservation_id bigint NOT NULL,
    CONSTRAINT payments_pkey PRIMARY KEY (id),
    CONSTRAINT uke7qdxh4fch1yfisduker8j6w2 UNIQUE (reservation_id)
);

CREATE TABLE IF NOT EXISTS public.productos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    categoria character varying(255) COLLATE pg_catalog."default",
    descripcion character varying(500) COLLATE pg_catalog."default",
    disponible boolean NOT NULL,
    imagen_url character varying(200) COLLATE pg_catalog."default",
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    precio double precision NOT NULL,
    stock integer NOT NULL,
    CONSTRAINT productos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.proveedores
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    activo boolean NOT NULL,
    ciudad character varying(50) COLLATE pg_catalog."default",
    contacto character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT proveedores_pkey PRIMARY KEY (id),
    CONSTRAINT ukb3k7hy6nk59ivbito83avgfyi UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.reservations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    end_date timestamp(6) without time zone NOT NULL,
    notes character varying(500) COLLATE pg_catalog."default",
    start_date timestamp(6) without time zone NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    total_amount numeric(38, 2) NOT NULL,
    updated_at timestamp(6) without time zone,
    tool_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT reservations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.tools
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    available boolean NOT NULL,
    category character varying(255) COLLATE pg_catalog."default",
    description character varying(500) COLLATE pg_catalog."default",
    image_url character varying(200) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    rental_price numeric(38, 2) NOT NULL,
    serial_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    stock integer NOT NULL,
    CONSTRAINT tools_pkey PRIMARY KEY (id),
    CONSTRAINT uko7tlm68n4sxgrhkw30glioayu UNIQUE (serial_number)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    active boolean NOT NULL,
    address character varying(200) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(15) COLLATE pg_catalog."default",
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username)
);

ALTER TABLE IF EXISTS public.admin_roles
    ADD CONSTRAINT fk3liyab508sfblqps0eqjhmjqk FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.admin_roles
    ADD CONSTRAINT fkghcw89q6jebq3c6kocnobjusr FOREIGN KEY (admin_id)
    REFERENCES public.admins (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.alquileres
    ADD CONSTRAINT fkafewqwflgd7xr3msws03qgqam FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.alquileres
    ADD CONSTRAINT fks5mnsr6xf4mmngcv5shhssm8n FOREIGN KEY (tool_id)
    REFERENCES public.tools (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT fkkga8j6hh54xf5hl3qiovlsa4l FOREIGN KEY (reservation_id)
    REFERENCES public.reservations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk6t7ctxgwv5ahht8vtcn3fxow5
    ON public.invoices(reservation_id);


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT fkp8yh4sjt3u0g6aru1oxfh3o14 FOREIGN KEY (reservation_id)
    REFERENCES public.reservations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uke7qdxh4fch1yfisduker8j6w2
    ON public.payments(reservation_id);


ALTER TABLE IF EXISTS public.reservations
    ADD CONSTRAINT fkb5g9io5h54iwl2inkno50ppln FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reservations
    ADD CONSTRAINT fkmyqbj92ndk9fsbtah3xnd6u0d FOREIGN KEY (tool_id)
    REFERENCES public.tools (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;